### ISSUE TITLE
Latest version of launcher can't be launched

### ISSUE THREAD

**Issue by damridk** [fn2006/PollyMC#33]
### Operating System

Windows

### Version of PollyMC

PollyMC 5.1

### Version of Qt

Launcher can't be launched so i don't know

### Description of bug

Launching a launcher shows a error about side-by-side configuration
![image](https://user-images.githubusercontent.com/116867826/199452287-8a30a1e1-7600-4b69-a8dc-cc91c6b08a4a.png)

### Steps to reproduce

Launch PollyMC 5.1

### Additional info
Here's the sxstrace.exe logs, hope they will help:
```
=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-US;en
	ManifestPath = C:\Users\User\idk\pollymc.exe
	AssemblyDirectory = C:\Users\User\idk\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Users\User\idk\pollymc.exe.
	INFO: Manifest Definition Identity is (null).
	ERROR: Line 3: The value  of attribute version in element assemblyIdentity is invalid.
ERROR: Activation Context generation failed.
End Activation Context Generation.
```
(I launched it several times)
### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by yum13241** [comment]
This happens to me too!

**Comment by fn2006** [comment]
Sorry about that, I forgot to test the windows build and it turns out I forgot to update something, I've fixed it and created a new release that you can download.

**Comment by yum13241** [comment]
Still doesn't work with the same error. I even tried extracting into a clean directory.
