### ISSUE TITLE
Merge from Prism to fix PrismLauncher/PrismLauncher#226

### ISSUE THREAD

**Issue by WGOS** [fn2006/PollyMC#38]
### Role

to play modded Minecraft

### Suggestion

Merge last changes from PrismLauncher

### Benefit

To fix problem related to updating mods when instance folder's name contains non-ASCII characters

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Greeings. It would've been nice to have this fix in PollyMC as it already arrived to Prism according to PrismLauncher/PrismLauncher#226

**Comment by fn2006** [comment]
I've merged the latest changes from Prism into develop, you can get a build for your platform from the actions section.

**Comment by offbeat-stuff** [comment]
the github page still shows forked from PolyMC/PolyMC
can that not be changed

**Comment by fn2006** [comment]
This fix is included in 5.2, closing.

> the github page still shows forked from PolyMC/PolyMC 
> can that not be changed

Nope, I've looked into this and it's impossible to change.
